name: Deploy to prod

on: workflow_call

# Это лишь примерные степы, как может выглядеть пайплайн
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to prod
        run: echo Просиходит деплой бекенда на прод

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to prod
        run: echo Просиходит деплой фронтенда на прод